services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-nextjs
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - nextjs_cache:/app/.next
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=2048
    restart: unless-stopped
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

volumes:
  nextjs_cache: